___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [13]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [14]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [15]:
np.array(my_list)

array([1, 2, 3])

In [16]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [18]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [20]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones(3)

array([1., 1., 1.])

In [23]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [24]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [25]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [26]:
# np.linspace(0,10,50) returns 50 evenly spaced numbers between 0 and 10 (inclusive).
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [27]:
# The np.eye(N) function creates an N x N identity matrix, 
# which has 1's on the diagonal and 0's elsewhere.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [28]:

# A uniform distribution is a type of probability distribution in which all values within a certain range are equally likely to occur.
# In NumPy, np.random.rand generates numbers from a uniform distribution over [0, 1), meaning every number in this interval has an equal chance of being selected.

# np.random.rand(2) generates a 1-dimensional array of 2 random numbers sampled from a uniform distribution over [0, 1)
np.random.rand(2)

array([0.73655651, 0.46612918])

In [29]:
# np.random.rand(5,5) creates a 5x5 array of random numbers drawn from a uniform distribution over [0, 1)
np.random.rand(5,5)

array([[0.64039839, 0.72301107, 0.31130631, 0.09079327, 0.80980013],
       [0.22684053, 0.03229712, 0.9805492 , 0.30447644, 0.45395038],
       [0.62769075, 0.30690748, 0.16893082, 0.94966769, 0.2034808 ],
       [0.79456371, 0.94511815, 0.52480981, 0.30751649, 0.34882274],
       [0.09562749, 0.4419188 , 0.98167936, 0.18325805, 0.22809619]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

#### The standard normal distribution is a special kind of normal (Gaussian) distribution with:
- **Mean of 0** (center of the distribution, i.e., the peak of the bell curve)
- **Standard deviation of 1** (controls the width/dispersion of the curve)

When drawing samples from a standard normal distribution:
- Most values will be close to 0
- Some values are negative, some are positive
- Extreme values (far from 0) are rare

**Example usage:**  
Create an array of 8 random numbers drawn from a standard normal distribution:
```python
data = np.random.randn(8)
print(data)
# Example output:
# array([-1.12,  0.76, -0.22,  0.87,  0.14, -0.70,  1.48, -0.96])
```

Notice how the numbers are centered around zero, and both positives and negatives are possible, with most numbers not too far from 0.

In [ ]:

# The standard normal distribution is a special case of the normal (Gaussian) distribution with a mean of 0 and a standard deviation of 1.
# In a standard normal distribution:
#   - The mean = 0 (center of the "bell curve")
#   - The standard deviation = 1 (spread/width of the bell curve)
# Most values fall near 0, with fewer values farther from 0, following the familiar bell-shaped curve.
# Values can be positive or negative, and the probability of extreme values decreases rapidly as you move away from 0.

# np.random.randn(2) generates a 1-dimensional array with 2 random numbers drawn from a standard normal distribution (mean 0, variance 1).
# How it works: For each element, NumPy samples from a "bell curve" (Gaussian/normal distribution), so most values will be near 0, but some can be higher or lower.

np.random.randn(2)

array([0.38588315, 0.14836483])

In [58]:
# np.random.randn(5, 5) generates a 5x5 array where each value is drawn from a standard normal distribution (mean 0, variance 1).
# That means each number is randomly chosen according to the bell curve of the normal distribution.
np.random.randn(5, 5)

array([[ 0.41247022, -1.33342996,  0.58762342, -0.27107616,  0.80758121],
       [-0.50853256, -0.73887876,  1.78033413, -0.43217731, -0.92059162],
       [-1.819772  ,  0.31392782,  0.20824436, -0.21177281, -1.52047451],
       [-0.06299094, -1.54377378, -0.28768342, -0.79531704, -0.46050186],
       [ 1.3628675 ,  0.1615568 , -1.94774849,  0.23143208, -0.57823023]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [67]:
np.random.randint(1,100)

56

In [68]:
np.random.randint(1,100,10)

array([16, 70,  6,  6, 70, 15, 55, 51, 19, 35])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [69]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [70]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [71]:
ranarr

array([41, 45, 48, 31, 37, 41, 41, 11,  4, 43])

## Reshape
Returns an array containing the same data with a new shape.

In [91]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [90]:
# print(arr.min(), end="\n")
# print(arr.max(), end="\n")
# print(arr.argmax(), end="\n")
# print(arr.argmin(), end="\n")
# print(arr.reshape(1,25), end="\n")
# print(arr.reshape(1,25).shape, end="\n")
# print(arr.reshape(25,1), end="\n")
# print(arr.reshape(25,1).shape, end="\n")

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [92]:
ranarr

array([41, 45, 48, 31, 37, 41, 41, 11,  4, 43])

In [75]:
ranarr.max()

np.int64(48)

In [76]:
ranarr.argmax()

np.int64(2)

In [77]:
ranarr.min()

np.int64(4)

In [78]:
ranarr.argmin()

np.int64(8)

## Shape

Shape is an attribute that arrays have (not a method):

In [86]:
# Vector
arr.shape

(25,)

In [87]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [95]:
arr.reshape(1,25).shape

(1, 25)

In [96]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [97]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [98]:
arr.dtype

dtype('int64')

# Great Job!